### ISSUE TITLE
/whereis returns buildings that don't necessarily match the building name. 

### ISSUE THREAD

**Issue by ahmadmunim** [uwindsorcss/css-discord-bot#71]
#### Expected Behaviour
If the prompt isn't a building that exists then it should return that the building isn't found and we need to consider ambiguous cases such as the prompt being `hall`
#### Actual Behaviour
Example: `/whereis hello` outputs `dillon` and `/whereis hall` outputs erie hall when other building names have the word hall in them
#### Steps to Reproduce
Have a stricter match regarding the prompts

**Comment by kilbouri** [comment]
Discord JS, helpfully, provides the way to [specify a finite value set](https://discordjs.guide/slash-commands/parsing-options.html#choices) for string options. Perhaps we have a list of locations and use the Options API instead of fuzzy matching?

**Comment by BorhanSaflo** [comment]
Addressed this issue in 4943a88

Regarding the first example, I've made changes to ensure that `/whereis search hello` will not be accepted since "hello" does not match any existing building.

For the second example, when a user enters `/whereis search hall`, the bot will now provide a list of suggestions containing all buildings that include the term "hall." This improvement allows users to select the desired building from the suggestions. However, if the user ignores the suggestions and continues to use just "hall" without selecting from the suggestions, the bot will just display the first building in the list that matches the term "hall." I believe this behavior is more user-friendly as it avoids showing an error message and instead offers a potential match.
